- doc/src/lec.m
- doc/src/readme.m
- doc/src/start.txt
- doc/src/lec.m: a (single) space is added between 2 brackets for dokuwiki compatibility (in the dokuwiki syntax, '[[' indicates the beginning of a internal link)
- doc/src/readme.m: '$' sign removed from "$WsCopyVar" and "$CsvSave*" to avoid misinterpretation by the Dokuwiki parser.
- doc/start.txt:
- pre-2019 installers removed
- new section for iodecmd64.exe
- section IODE implementions (previously "IODE uses") reformulated
> jmp_doc_typos

- .github/workflows/github-actions-iode.yml
For artifacts, see [Storing workflow data as artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts).
> GITHUB ACTIONS: Simplify build_cython job + upload resulting files as artifact

- api/iodebase.h
- api/report/engine/b_rep_super.c
- api/report/undoc/b_view.c
- gui/iode_objs/models/gsample_table_model.cpp
- gui/iode_objs/models/gsample_table_model.h
- gui/iode_objs/views/gsample_table_view.h
- gui/legacy/sb_gui.c
- gui/menu/print_graph/print_variables.cpp
- gui/menu/print_graph/print_variables.h
- gui/super.cpp
- gui/super.h
@jmpplan  @gbryon 
FYI, because of how my C++ API and Qt interface are implemented, I had no choice but to change the signature of the functions `T_view_tbl()` and `T_view_tbl_super()`. This had some consequences on the way functions in `b_view.c` are implemented.
See commit 48ff9bcd078d9efb6b382638ef6ced6596ea69f6 below
This of course breaks the code of the DOS interface but we still have the (good old) `iode_src` repository and the DOS interface is not supposed to be maintained in the future.
> GUI: Fixed report functions $ViewVar and $ViewTbl

- api/report/engine/b_rep_cmds.c
The report function `RP_warning()` now calls `kwarning("%s", arg)` instead of `kwarning(arg)` to avoid crashes if arg contains `%`
> JMP - BUG in report example.ldo fixed

- gui/custom_widgets/tab_widget.cpp
- gui/custom_widgets/tab_widget.h
- gui/custom_widgets/tab_widget_abstract.cpp
- gui/custom_widgets/tab_widget_abstract.h
- gui/main_window.cpp
Broken commit is e7cb574bb7e2ebf3c83a817c57389de29fd4b64c
> GUI: Fix broken commit e7cb574 + rewritten loadSettings() and saveSettings() from the QIodeTabWidget class 

- CMakeLists.txt
- api/CMakeLists.txt
- cmd/CMakeLists.txt
- cpp_api/CMakeLists.txt
- cpp_api/KDB/kdb_global.cpp
- cpp_api/KDB/kdb_global.h
- doc/changelog/versions/v7.0-beta.4.rst.inc
- scr4/CMakeLists.txt
- tests/sandbox/CMakeLists.txt
- tests/sandbox/testalign.c
- tests/test_c_api/CMakeLists.txt
@jmpplan Surprisingly, just removing the compile option `Z1` didn't raised any error from the C and C++ tests and from running the report from the folder `tests\cmd`. 
You told me it would be complicated to get rid of the alingment on 1 byte. 
Seems it does not ?!?
Did I miss something ?
> SCR4 + C API: compile without option Z1 (use default alignment)

- CMakeLists.txt
- api/iode.h
- api/iodeapi.h
- api/iodebase.h
- api/lec/l_link.c
- api/objs/k_tbl.c
- api/report/commands/b_model.c
- api/report/commands/b_xode.c
- api/report/engine/b_rep_cmds.c
- api/report/engine/b_rep_fns.c
- api/report/engine/b_rep_super.c
- api/report/engine/b_rep_syntax.c
- api/report/undoc/b_api.c
- api/report/undoc/b_view.c
- api/simulation/k_sim_exo2endo.c
- api/simulation/k_sim_main.c
- api/simulation/k_sim_order.c
- api/simulation/k_sim_scc.c
- cpp_api/compute/simulation.cpp
- cpp_api/compute/simulation.h
- tests/test_c_api/test1.c
- tests/test_c_api/test_c_api.cpp
- tests/test_cpp_api/test_simulation.cpp
- new command `$silent`
- new function `@version()` 
- command `$msg`: bug fixed
- new `@functions` related to simulations:
```
@SimSortNbPasses()  Last "nbtri" parameter
@SimSortAlgo()      Last sort parameter: "Connex", "Triangulation" or "None"
@SimInitValues()    Last starting values parameter
@SimCpuScc()        Time in ms spent to compute Connex Components
@SimCpuSort()       Time in ms spent to reorder the interdependent block of the model
@SimCpu(period)     Time in ms elapsed during last simulation of the specified period
@SimNorm(period)    Convergence criterion reached for the given period during last simulation
@SimNIter(period    Number of iteration needed to reach a solution for the given period during last simulation
```
In a simulation, when an exchange endo-exo is …
> API: synchonisation iode-dos 6.70 api -> iode 7.0 api

- tests/test_nanobind/test_iode.py
- tests/test_python/test_iode.py
@jmpplan Please repeat the change made in this PR in the private iode repository.
See [issue 5](https://github.com/plan-be/iode_dos/issues/5) from the private iode repository.
> TESTS PYTHON: fixed test_iode_model_simulate_exchange() (due to PR #373)

- cpp_api/KDB/kdb_variables.cpp
- cpp_api/KDB/kdb_variables.h
- python_api/CMakeLists.txt
- python_api/py_numpy.h
- python_api/pyiode.cpp
- tests/test_nanobind/test_iode.py
- tests/test_python/test_iode.py
@jmpplan You may be interested to see in how `nanobind` deals with Numpy arrays by looking at the present PR.
Note that I also modified the `test_iode.py` file in the `tests/test_python` folder (folder to test the iode Python module compiled with `cython`)
See [here](https://nanobind.readthedocs.io/en/latest/ndarray.html) for more details.
> PYTHON: (nanobind) added the get_var_as_ndarray() function

- cpp_api/KDB/kdb_equations.cpp
- cpp_api/KDB/kdb_equations.h
- cpp_api/objects/equation.cpp
- cpp_api/objects/equation.h
- python_api/py_constants.cpp
- python_api/py_objs.cpp
- python_api/py_objs.h
- tests/test_nanobind/test_iode.py
@jmpplan Please take a look of
- the change I made in the file `test_iode.py` -> commit abc441d3ec47e189207a3764231613b77a131ec1 
- how my C++ class Equation is exported to Python -> files [equation.h](https://github.com/plan-be/iode/blob/master/cpp_api/objects/equation.h) and [equation.cpp](https://github.com/plan-be/iode/blob/master/cpp_api/objects/equation.cpp) + commit 4500283d3e6dfd4a5041850795e7559e17b30e8a
- how the Python methods `get_eqs()` and `set_eqs()` are defined -> method [KDBEquations::add](https://github.com/plan-be/iode/blob/master/cpp_api/KDB/kdb_equations.cpp#L26) + global C++ variable [Equations](https://github.com/plan-be/iode/blob/master/cpp_api/KDB/kdb_equations.h#L60) + commit e886ec130316b8a6d5d333c562d0d63db9c193ec
Note that in the KDBEquations::add() method, I …
> PYTHON (NANOBIND): Exported the C++ class Equation + enabled get_eqs() and set_eqs()

- doc/changelog/versions/v7.0-beta.5.rst.inc
- gui/iode_objs/models/abstract_table_model.cpp
- gui/iode_objs/models/abstract_table_model.h
- gui/tabs/iode_objs/tab_database_abstract.h
* Fixed IODE objects tabs displaying the wrong filename when the filter is used (#398)
* Fixed interface crashing when the user tries to clear a KDB while the filter is used (#404)
> GUI: Fixed issues #398 and #404

- doc/changelog/versions/v7.0-beta.5.rst.inc
- gui/iode_objs/models/abstract_table_model.cpp
- gui/iode_objs/models/abstract_table_model.h
- gui/tabs/iode_objs/tab_database_abstract.h
- gui/tabs/tab_abstract.h
- gui/text_edit/report_editor.cpp
> GUI: Use QString::fromLocal8Bit() and QString::toLocal8Bit() to handle paths with special characters in Windows

- doc/changelog/versions/v7.0.0-beta.6.rst.inc
- gui/main_widgets/iode_command.cpp
- gui/main_window.cpp
- gui/tabs/iode_objs/tab_database_abstract.h
This could also fix issue #416
> GUI: Fixed user interface crashing when deleting an IODE object while a subset of the IODE database is displayed (issue 473)

- .gitignore
- pyiode/cythonize_iode.py.in
- pyiode/iode.pxi
- pyiode/iode.pyx
- pyiode/pyiode_sample.pyx
- pyiode/pyiode_ws.pyx
- pyiode/s_iode.c
@jmpplan I have adapted the current pyiode `cythonize_iode.py.in` file + some `.pyx` files so that `pyiode` can bind with C++ code. See commit messages below.
Commit messages:
- GITIGNORE: ignore generated file /pyiode/iode.cpp
- PYIODE: prepare pyiode for C++
(cythonize_iode.py.in)
- ask Cython to compile pyiode using the C++ compiler
instead of the C compiler
(iode.pyx)
- include C++ std libraries <string> and <vector>
(s_iode.c)
- added free_tbl(char** tbl) function for compatibility with C++
(pyiode_sample.pyx)
- replaced SCR_free_tbl() by free_tbl()
(pyiode_ws.pyx)
- replaced SCR_free_tbl() by free_tbl()
- PYIODE: (cythonize_iode.py.in)
- added the IODE C++ API to the libraries to link with
> PYIODE: prepare to bind with C++ code 

- api/b_errors.c
- api/iodebase.h
- cpp_api/KDB/kdb_abstract.cpp
- cpp_api/KDB/kdb_global.cpp
- cpp_api/KDB/kdb_identities.cpp
- cpp_api/KDB/kdb_variables.cpp
- cpp_api/compute/estimation.cpp
- cpp_api/compute/estimation.h
- cpp_api/utils/utils.h
- tests/test_cpp_api/test_estimation.cpp
- tests/test_cpp_api/test_kdb_identities.cpp
The purpose is to be able to rely on the C++ exceptions and the C++ `try/catch` mechanism. 
@jmpplan For your information, I added the C function `get_last_error()` (which returns a char*) in the source file `b_error.c`
> C/C++ API: added C and C++ functions get_last_error() to transform C error messages into C++ exceptions

- api/ascii/k_cceqs.c
- api/estimation/e_dftest.c
- api/estimation/e_print.c
- api/iode.h
- api/iodeapi.h
- api/iodebase.h
- api/k_exec.c
- api/objs/k_pack.c
- api/objs/k_wsvar.c
- api/report/commands/b_data.c
- api/report/commands/b_htol.c
- api/report/undoc/b_api.c
- api/utils/per.c
- scr4/s_probas.h
- tests/data/fun2.ae
- tests/data/rep_fns.ref.a2m
- tests/data/rep_fns.rep
- tests/test_c_api/test1.c
- tests/test_c_api/test_c_api.cpp
Identities
----------
- generated trace file improved to indicate the source files for each variable and scalar needed to compute identities.
- when the execution sample is empty, the current WS sample is used (if defined)
Python module
-------------
New functions for the iode.pyd module:
- Simulation: `IodeModelCpuSort()` and `IodeModelCpuSCC()`: new fonctions to report the CPU needed to decompose and reorder a model
- Error Messages: `IodeAddErrorMsg()`, `IodeDisplayErrorMsgs()`, `IodeClearErrorMsgs()`: new fonctions to add, display and reset error messages created by the fns `B_seterrn()` and `B_seterror()`
- Identities: `IodeExecuteIdts()` for the implementation `idt_execute()`
Ascii conversion
----------------
In equation ascii format, when the SAMPLE is empty, no informations about …
> Synchronize API between iode_dos and iode qt 

- cpp_api/KDB/kdb_variables.h
- cpp_api/common.h
- cpp_api/compute/estimation.h
- cpp_api/compute/simulation.h
- cpp_api/objects/equation.h
Note: Cython does not allow to declare C++ std::array
> C++ API: replaced std::array global variables by std::vector

- pyiode/iode_python.pyx
- pyiode/pyiode_cdef.pyx
- pyiode/pyiode_data.pyx
- pyiode/pyiode_estim.pyx
- pyiode/pyiode_larray.pyx
- pyiode/pyiode_lec.pyx
- pyiode/pyiode_model.pyx
- pyiode/pyiode_objs.pyx
- pyiode/pyiode_reports.pyx
- pyiode/pyiode_sample.pyx
- pyiode/pyiode_util.pyx
- pyiode/pyiode_wrt.pyx
- pyiode/pyiode_ws.pyx
@jmpplan 
Basically I renamed the functions that are not supposed to be exposed to the final users by prepending their names by an underscore.
In Python, objects or functions or classes starting with an underscore are not imported when you do `from iode import *`
See [this link](https://stackoverflow.com/a/8689983)
> PYIODE: hide utility functions to users

- pyiode/iode_python.pxd
- pyiode/pyiode_cdef.pyx
- pyiode/pyiode_data.pyx
- pyiode/pyiode_estim.pyx
- pyiode/pyiode_exec.pyx
- pyiode/pyiode_larray.pyx
- pyiode/pyiode_model.pxd
- pyiode/pyiode_model.pyx
- pyiode/pyiode_reports.pyx
- pyiode/pyiode_util.pxd
- pyiode/pyiode_util.pyx
- pyiode/pyiode_ws.pyx
IODE python module
==================
Identities
----------- 
New function `idt_execute()` to execute a list of identities: 
```
idt_execute(sample: Optional[Union[str, List[str]]] = None, 
idt_list: Optional[Union[str, List[str]]] = None, 
var_files: Optional[Union[str, List[str]]] = None, 
scl_files: Optional[Union[str, List[str]]] = None,
trace: bool = False):
```
Model simulation
----------------
New functions: 
|Syntax|Description|
|:---|:---|
| `model_calc_scc()` | decompose a model into lists of Strong Connex Components and reorder the interdependent block list
| `model_simulate_scc()`| simulate a model defined by its SCC
| `model_simulate_maxit() -> int             ` | Returns the maxit parameter of the last simulation   
| `model_simulate_eps() -> float             ` | Returns …
> Import iode-python module from IODE-DOS  6.71

- .github/workflows/github-actions-nsis.yml
- .github/workflows/github-actions-release.yml
Fixes [Dependabot alerts](https://github.com/advisories/GHSA-cxww-7g56-2vh6/dependabot) for action `download-artifact`
> GITHUB ACTIONS: bumped action download-artifact to version v4

- pyiode/iode_database/abstract_database.pyx
- pyiode/iode_database/tables_database.pyx
- pyiode/objects/table.pxd
- pyiode/objects/table.pyx
> PYTHON: updating the global Tables database when the syntax tables[name].attribute = value is used

- doc/source/changes/v7.0.0.rst.inc
- pyproject.toml.in
As the existing `iode` package on PyPi has been kindly renamed to another name by @jugangdae
> PYTHON: (pyproject.toml.in) renamed project as iode

- .github/workflows/github-actions-python.yml
- doc/requirements.txt
- gui/iode_gui/abstract_main_window.py
- gui/iode_gui/iode_objs/views/abstract_table_view.py
- gui/iode_gui/iode_objs/views/table_view.py
- gui/iode_gui/main_widgets/iode_command.py
- gui/iode_gui/main_window.py
- gui/iode_gui/menu/file/file_settings.py
- gui/iode_gui/menu/print_graph/print_tables.py
- gui/iode_gui/menu/print_graph/print_variables.py
- gui/iode_gui/print/print_file_dialog.py
- gui/iode_gui/print/print_file_dialog.ui
- gui/iode_gui/settings.py
- gui/iode_gui/tabs/iode_objs/tab_computed_table.py
- gui/iode_gui/tabs/iode_objs/tab_database.py
- gui/iode_gui/tabs/tab_abstract.py
- gui/iode_gui/tabs/tab_report.py
- gui/iode_gui/text_edit/report_editor.py
- pyiode/pyproject.toml.in
> GUI PYTHON: save settings to QSettings(Scope.UserScope) when the GUI is opened using the view_workspace() function

- api/estimation/e_error.c
- api/estimation/e_est.c
- api/iodebase.h
- api/messages.hpp
- tests/test_c_api/test_c_api.cpp
@jmpplan Do you remenber why the function `E_msg_n()` was commented ?
A (new) IODE user complained that 'Estimation: error 6' is not very very *helpful* (if you know what I mean?) ;)
> C API: (e_error.c/e_est.c) resurrected the E_msg_n() function

- doc/source/changes/v7.0.4.rst.inc
- gui/iode_gui/iode_objs/edit/edit_table.ui
- gui/iode_gui/iode_objs/edit/edit_table_model.py
- gui/iode_gui/iode_objs/edit/edit_table_view.py
- gui/iode_gui/iode_objs/estimation/estimation_coefs.py
- gui/iode_gui/iode_objs/views/computed_table_view.py
- gui/iode_gui/tabs/iode_objs/tab_computed_table.py
Added color theme support to the views of computed tables, estimation coefficients and edition of IODE tables
fix #1061
> GUI: fixing cells content not visible when editing an IODE table if Windows OS is in dark mode
