.github/actions/build_api/action.yml
.github/actions/install_qt/action.yml
.github/actions/test_api/action.yml
.github/workflows/github-actions-iode.yml

See [Creating a composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) and this [Stackoverflow link](https://stackoverflow.com/a/75279262 ) for details.

GITHUB ACTIONS (GUI): Use Artifacts to save and restore output between build_and_test_api and build_gui jobs

---

.gitignore
gui/custom_widgets/tab_widget_abstract.cpp
gui/custom_widgets/tab_widget_abstract.h
gui/super.cpp
gui/tabs/tab_text_abstract.cpp
pyiode/makepy.bat

fixing issues #262, #264 and #265

GUI: $msg -> QMessageBox::information() + do not reload file when saving the tab content

---

gui/custom_widgets/report_editor.cpp
gui/custom_widgets/tab_widget.cpp
gui/custom_widgets/tab_widget_abstract.cpp
gui/custom_widgets/tab_widget_abstract.h
gui/tabs/tab_abstract.h
gui/tabs/tab_report.h
gui/tabs/tab_text_abstract.cpp
tests/data/1. sub-dir/rep_expand.rep
tests/data/1. sub-dir/rep_proc.rep

GUI: fixed issues 254 and 274 + miscellaneous

---

cpp_api/KDB/kdb_abstract.h
gui/custom_widgets/tab_widget.cpp
gui/custom_widgets/tab_widget.h
gui/custom_widgets/tab_widget_abstract.cpp
gui/iode_objs/models/abstract_table_model.h
gui/main_window.cpp
gui/tabs/tab_abstract.h
gui/tabs/tab_database.h
gui/tabs/tab_text_abstract.cpp
gui/tabs/tab_text_abstract.h

GUI: double click on a IODE DB file in the File Explorer asks the user if (s)he wants to reload it

---

.github/workflows/github-actions-debug.yml
CMakeLists.txt
tests/test_python/CMakeLists.txt

CMAKE + GITHUB ACTIONS: miscellaneous

---

cpp_api/common.h
doc/changelog/versions/v7.0-beta.4.rst.inc
gui/custom_widgets/print_file_dialog.cpp
gui/custom_widgets/print_file_dialog.h
gui/custom_widgets/tab_widget.cpp
gui/custom_widgets/tab_widget_abstract.cpp
gui/iode_objs/views/abstract_table_view.cpp
gui/iode_objs/views/abstract_table_view.h
gui/iode_objs/views/comments_view.cpp
gui/iode_objs/views/comments_view.h
gui/iode_objs/views/equations_view.cpp
gui/iode_objs/views/equations_view.h
gui/iode_objs/views/identities_view.cpp
gui/iode_objs/views/identities_view.h
gui/iode_objs/views/lists_view.cpp
gui/iode_objs/views/lists_view.h
gui/iode_objs/views/scalars_view.cpp
gui/iode_objs/views/scalars_view.h
gui/iode_objs/views/tables_view.cpp
gui/iode_objs/views/tables_view.h
gui/iode_objs/views/variables_view.cpp
gui/iode_objs/views/variables_view.h
gui/menu/print_graph/print_abstract.cpp
gui/tabs/tab_text.cpp
gui/tabs/tab_text.h
gui/utils.h

GUI: Opens files with .rtf extension with Microsoft Word by default

---

doc/changelog/versions/v7.0-beta.5.rst.inc
gui/CMakeLists.txt
gui/iode_objs/edit/edit_iode_obj.cpp
gui/iode_objs/edit/edit_iode_obj.h
gui/iode_objs/edit/edit_iode_obj.ui
gui/iode_objs/views/comments_view.h
gui/iode_objs/views/identities_view.h
gui/iode_objs/views/lists_view.h
gui/tabs/iode_objs/tab_database.h

GUI: Enabled editing Comments, Identities and Lists in box dialogs (issue 364)

---

cpp_api/objects/table.cpp
cpp_api/objects/table.h
doc/changelog/versions/v7.0-beta.5.rst.inc
gui/iode_objs/edit/edit_table_model.cpp
tests/test_cpp_api/test_table.cpp

GUI: Edit Table -> line of type CELL -> if new text contains a double quotes, then it is a STRING cell, otherwise it is a LEC cell (issue 363)

---

gui/iode_objs/edit/edit_equation.cpp
gui/iode_objs/edit/edit_equation.h
gui/iode_objs/misc/unit_root.cpp
gui/iode_objs/models/scalars_model.cpp
gui/super.cpp
gui/tabs/iode_objs/tab_numerical_values.h

Recent changes are:
- the C++ classe Scalar now inherits from the C struct SCL
- the C++ classe Equation now inherits from the C struct EQ
- the signature of the super function `T_view_tbl_super()` has been reset to `T_view_tbl_super(TBL *tbl, char *smpl, char* name)`

GUI: fixed code of GUI no longer compiling due to recent updates of the C and C++ API

---

python_api/CMakeLists.txt
python_api/py_constants.cpp
python_api/py_constants.h
python_api/py_numpy.h
python_api/py_objs.cpp
python_api/py_objs.h
python_api/py_sample.cpp
python_api/py_sample.h
python_api/py_ws.cpp
python_api/py_ws.h
python_api/pyiode.cpp
tests/test_nanobind/CMakeLists.txt
tests/test_python/CMakeLists.txt

PYTHON: (NANOBIND) Cleanup - Splitted definition of Python functions and classes into several files

---

.github/workflows/github-actions-python.yml
CMakeLists.txt
CONTRIBUTE.md
cpp_api/KDB/kdb_variables.cpp
cpp_api/KDB/kdb_variables.h
cpp_api/time/sample.cpp
cpp_api/time/sample.h
pyproject.toml.in
python_api/iode/__init__.py
python_api/iode/convert_pandas.py
python_api/py_numpy.h
python_api/py_objs.cpp
tests/test_cpp_api/test_kdb_variables.cpp
tests/test_python/CMakeLists.txt
tests/test_python/test_iode.py

And updated the pyproject.toml to include pytest options
@jmpplan @yvdabb  
Note that with the new settings of pytest added here (in pyproject.toml.in), you just need to run `pytest` without any arguments in the root directory of the project
See commit https://github.com/plan-be/iode/pull/425/commits/4fc917ceed7d12f8b620af6019574cdac42ad027 in the present PR

PYTHON: (nanobind) Implemented df_to_ws() and ws_to_df() functions

---

cpp_api/KDB/kdb_abstract.cpp
cpp_api/compute/estimation.cpp
cpp_api/compute/estimation.h
cpp_api/objects/equation.cpp
cpp_api/objects/equation.h
doc/changelog/versions/v7.0-beta.5.rst.inc
gui/iode_objs/edit/edit_equation.cpp
gui/iode_objs/edit/edit_equation.h
gui/iode_objs/estimation/estimation_coefs.h
gui/iode_objs/estimation/estimation_results.cpp
gui/iode_objs/estimation/estimation_results.h
tests/test_cpp_api/test_equation.cpp
tests/test_cpp_api/test_estimation.cpp

@jmpplan 
This PR is the adaptation of `o_est.c` from the DOS GUI for the QT GUI.
To be able to make some automatic tests, I moved a part of the content of the `ODE_blk_...()` functions in the C++ API and the other part in the Qt interface.

C++ API & GUI: rewritten classes Estimation (C++ API) and EditEquationDialog (GUI) to reproduce the Edit Equation box from the DOS GUI

---

doc/changelog/versions/v7.0.0-beta.6.rst.inc
gui/main_widgets/iode_command.cpp
gui/main_widgets/iode_command.h

@yvdabb I found some time to work on the issue #386 
I realize it was not that easy to work on it since it requires to understand the global structure of the GUI and to be comfortable to play with QSettings, QListString and iterator classes
Feel free to read how I implemented it it this Pull Request.

GUI: remember the last 20 executed commands

---

pyiode/iode_python.pxi
pyiode/pyiode_larray.pyx
pyiode/pyiode_pandas.pyx
pyiode/pyiode_sample.pyx

@jmpplan I made some changes in pyiode so that `larray` becomes optional

PYIODE: made the library larray optional

---

.gitignore
CMakeLists.txt
pyiode_2023/CMakeLists.txt
pyiode_2023/cythonize_iode.py.in
pyiode_2023/iode.pxi
pyiode_2023/iode.pyx
pyiode_2023/makepy.bat
pyiode_2023/pyiode_cdef.pyx
pyiode_2023/pyiode_data.pyx
pyiode_2023/pyiode_estim.pyx
pyiode_2023/pyiode_exec.pyx
pyiode_2023/pyiode_larray.pyx
pyiode_2023/pyiode_lec.pyx
pyiode_2023/pyiode_model.pyx
pyiode_2023/pyiode_objs.pyx
pyiode_2023/pyiode_pandas.pyx
pyiode_2023/pyiode_print.pyx
pyiode_2023/pyiode_reports.pyx
pyiode_2023/pyiode_sample.pyx
pyiode_2023/pyiode_util.pyx
pyiode_2023/pyiode_wrt.pyx
pyiode_2023/pyiode_ws.pyx
pyiode_2023/s_iode.c

@jmpplan I created a special /pyiode_2023 folder in which I copy/pasted the last version version from the IODE-DOS repository

PYIODE: create folder pyiode_2023 

---

pyiode/iode/__init__.py
pyiode/iode/deprecated/compat_larray.py
pyiode/iode/deprecated/compat_pandas.py
pyiode/iode/deprecated/iode_objects.py
pyiode/iode/deprecated/time.py
pyiode/iode/deprecated/workspace.py
pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/comments_database.pyx
pyiode/iode_database/equations_database.pyx
pyiode/iode_database/global_funcs_database.pyx
pyiode/iode_database/identities_database.pyx
pyiode/iode_database/lists_database.pyx
pyiode/iode_database/scalars_database.pyx
pyiode/iode_database/tables_database.pyx
pyiode/iode_database/variables_database.pyx
pyiode/model.pyx
pyiode/objects/equation.pyx
pyiode/objects/table.pyx
tests/test_python/test_iode.py

Also created global variables comments, equations, identities, lists, scalars, tables and variables

PYIODE: forbid users to call constructor of Comments, Equations, Identities, Lists, Scalars, Tables and Variables

---

doc/source/equivalence.rst

DOC (PYTHON): added IODE Data commands <--> Pyiode functions/methods

---

pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/comments_database.pyx
pyiode/iode_database/equations_database.pyx
pyiode/iode_database/identities_database.pyx
pyiode/iode_database/lists_database.pyx
pyiode/iode_database/scalars_database.pyx
pyiode/iode_database/tables_database.pyx
pyiode/iode_database/variables_database.pyx

- implemented copy() in _AbstractDatabase
- implemented _unfold_key() in _AbstractDatabase
- updated `__getitem__` so that it can return a subset of an IODE database
- updated `__setitem__` to be able to update/add several IODE objects at once
- updated `__delitem__` to be able to delete several IODE objects at once

PYIODE: replace Database.subset() by Database[key] + added Database.copy() (issue 511)

---

pyiode/iode_database/variables_database.pyx

PYIODE: improved cython of the Variables class (following suggestion from PR #545) 

---

doc/source/api.rst
doc/source/equivalence.rst
pyiode/iode_database/equations_database.pyx
pyiode/objects/equation.pyx

PYIODE: implemented estimate() method in the Equation class

---

pyiode/util.pyx

PYIODE: (util) fixed returned value by is_NA()

---

doc/source/api.rst
pyiode/compute/estimation.pyx
pyiode/computed_table/computed_table.pyx
pyiode/iode_database/abstract_database.pyx
pyiode/objects/table.pyx

following the suggestions made by @gdementen in the PR #545

PYIODE: updated the Python Table class

---

pyiode/time/period.pyx

following suggestions from @gdementen in PR #545

PYIODE: update the Python Period class

---

doc/source/api.rst
pyiode/iode_database/variables_database.pyx
pyiode/lec.pyx
pyiode/objects/equation.pyx
pyiode/time/period.pyx
pyiode/time/sample.pyx

according to suggestions made by @gdementen in PR #545

PYIODE: updated the Python Sample class

---

doc/source/api.rst
doc/source/equivalence.rst
pyiode/compute/estimation.pyx
pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/comments_database.pyx
pyiode/iode_database/equations_database.pyx
pyiode/iode_database/identities_database.pyx
pyiode/iode_database/lists_database.pyx
pyiode/iode_database/scalars_database.pyx
pyiode/iode_database/variables_database.pyx
pyiode/objects/equation.pyx

PYIODE: (Database) property names + implemented __iter__ + updated __setitem__ for IODE lists

---

doc/source/api.rst
pyiode/iode_database/comments_database.pyx
pyiode/iode_database/equations_database.pyx
pyiode/iode_database/identities_database.pyx
pyiode/iode_database/lists_database.pyx
pyiode/iode_database/scalars_database.pyx
pyiode/iode_database/variables_database.pyx

PYIODE: (Database) added property series and df

---

.github/workflows/github-actions-python.yml
CONTRIBUTE.md
doc/requirements.txt
generate_stub_files.py.in
pyiode/CMakeLists.txt
pyproject.toml.in

PYIODE: update generate_stub_files to make it work on Github Actions

---

doc/source/api.rst
pyiode/compute/simulation.pyx
pyiode/iode/__init__.py
pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/cpp_api_database.pxd
pyiode/iode_database/identities_database.pyx
pyiode/iode_python.pyx
pyiode/objects/identity.pxd
pyiode/objects/identity.pyx
tests/test_python/test_cython_iode.py

PYTHON: Exported the C++ class Identity to Python

---

pyiode/iode_database/equations_database.pyx
pyiode/objects/equation.pyx
pyiode/objects/identity.pyx
pyiode/objects/scalar.pyx
pyiode/objects/table.pyx

PYTHON: implemented the special method __copy__ in the classes  Equation, Identity, Scalar and Table

---

doc/source/tutorial/getting_started.ipynb
pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/cpp_api_database.pxd
pyiode/iode_database/equations_database.pyx
pyiode/objects/equation.pxd
pyiode/objects/equation.pyx
pyiode/time/period.pxd
pyiode/time/sample.pxd

PYTHON: update the global Equations database when the syntax equations[name].attribute = value is used

---

gui/iode_gui/iode_objs/delegates/scalars_delegate.py
gui/iode_gui/iode_objs/delegates/variables_delegate.py
gui/iode_gui/iode_objs/models/abstract_table_model.py
gui/iode_gui/iode_objs/models/computed_table_model.py
gui/iode_gui/iode_objs/models/numerical_table_model.py
gui/iode_gui/iode_objs/models/table_model.py
gui/iode_gui/iode_objs/views/abstract_table_view.py
gui/iode_gui/iode_objs/views/table_view.py
gui/iode_gui/tabs/iode_objs/tab_database.py
gui/iode_gui/tabs/iode_objs/tab_database_abstract.py
gui/iode_gui/util/double_validator.py
pyiode/iode_database/variables_database.pyx
tests/test_python/test_iode.py

GUI PYTHON: added possibility to select a range of periods for Variables

---

doc/source/api.rst
pyiode/objects/table.pyx

PYTHON: (Table) added the title property

---

gui/iode_gui/iode_objs/models/computed_table_model.py
gui/iode_gui/iode_objs/views/numerical_view.py

GUI PYTHON: fixed copying values from the context menu for the Variables tab

---

gui/iode_gui/main_widgets/tab_widget/tab_widget.py

GUI PYTHON: fixed CTRL + S sending the activatedAmbiguously() signal 

---

pyiode/iode_database/variables_database.pyx

PYTHON: (Variables) implemented the special method __array__

---

doc/source/api.rst
gui/iode_gui/__init__.py.in
gui/iode_gui/abstract_main_window.py
gui/iode_gui/main.py
gui/iode_gui/main_widgets/file_explorer/file_explorer.py
gui/iode_gui/main_widgets/iode_command.py
gui/iode_gui/main_widgets/tab_widget/tab_widget.py
gui/iode_gui/main_window.py
gui/iode_gui/settings.py
gui/iode_gui/tabs/iode_objs/tab_computed_table.py
gui/iode_gui/tabs/iode_objs/tab_database.py
gui/iode_gui/tabs/tab_abstract.py
gui/iode_gui/tabs/tab_report.py
gui/iode_gui/utils.py.in
gui/run_test_gui.py
pyiode/iode/__init__.py
pyiode/iode/gui.py
tests/test_python/test_gui.py

PYTHON: (gui.py) implemented the view_workspace() function to open the iode-gui from a Python script

---

gui/iode_gui/iode_objs/views/numerical_view.py

GUI PYTHON: (NumericalTableView) fixed self.allow_to_paste actually not set in the setup() method

---

cpp_api/compute/estimation.cpp
cpp_api/compute/simulation.cpp
cpp_api/utils/utils.h
gui/iode_gui/iode_objs/edit/edit_equation.py
gui/iode_gui/iode_objs/estimation/estimation_results.py
gui/iode_gui/menu/compute/compute_model.py
gui/iode_gui/menu/compute/compute_scc_decomposition.py
gui/iode_gui/menu/compute/compute_scc_simulation.py
gui/iode_gui/menu/compute/compute_simulation.py
pyiode/compute/estimation.pyx
pyiode/compute/simulation.pyx
pyiode/iode/__init__.py
pyiode/iode/util.py
pyiode/iode_database/equations_database.pyx
pyiode/objects/equation.pyx
pyiode/util.pyx
pyiode/wrt.pyx
tests/test_python/test_cython_iode.py
tests/test_python/test_iode.py

PYIODE: made estimation and simulation methods to return a warning when failing

---

doc/source/api.rst
doc/source/tutorial/getting_started.ipynb
pyiode/iode_database/abstract_database.pyx
pyiode/iode_database/cpp_api_database.pxd
pyiode/iode_database/variables_database.cpp
pyiode/iode_database/variables_database.pyx

PYTHON: (Variables) implemented the arithmetic operators +, -, *, /, **, +=, -=, *= and /=

---

doc/source/tutorial/getting_started.ipynb
pyiode/iode_database/variables_database.pyx

- __sub__, __rsub__, __isub__,
- __mul__, __rmul__, __imul__,
- __truediv__, __rtruediv__, __itruediv__,
- __pow__

PYTHON: (Variables) added missing docstring and doctests for the -, *, / and ** operators

---

doc/source/api.rst
pyiode/iode_database/abstract_database.pyx
pyiode/objects/equation.pyx

PYTHON: (IodeDatabase) implemented the new_detached() method to create a new empty detached database

---

gui/iode_gui/main.py
gui/iode_gui/main_window.py
gui/run_test_gui.py

GUI PYTHON: (main.py) pull modified or reassigned variables from the IPython kernel back to the caller frame

---

pyiode/iode_database/variables_database.pyx
tests/test_python/test_iode.py

PYTHON: (Variables) made to_numpy() to return a 1D array when the subset contains only 1 variable

---

gui/iode_gui/iode_objs/edit/edit_table.py
gui/iode_gui/main_widgets/file_explorer/file_explorer.py
gui/iode_gui/main_widgets/tab_widget/tab_widget.py

GUI PYTHON: (Table Edit) fixed inserting line before or after current line done at the wrong place

---

gui/iode_gui/abstract_main_window.py
gui/iode_gui/iode_objs/edit/edit_equation.py
gui/iode_gui/iode_objs/edit/edit_iode_obj.py
gui/iode_gui/iode_objs/new/add_object.py
gui/iode_gui/main_widgets/iode_command.py
gui/iode_gui/main_widgets/tab_widget/tab_widget.py
gui/iode_gui/main_window.py
gui/iode_gui/menu/compute/compute_identities.py
gui/iode_gui/menu/compute/compute_model.py
gui/iode_gui/menu/compute/compute_scc_decomposition.py
gui/iode_gui/menu/compute/compute_simulation.py
gui/iode_gui/menu/data/duplicate.py
gui/iode_gui/menu/data/edit_tables.py
gui/iode_gui/menu/data/list_calculus.py
gui/iode_gui/menu/data/scan_objects.py
gui/iode_gui/menu/data/sort_expand_list.py
gui/iode_gui/menu/print_graph/graph_tables.py
gui/iode_gui/menu/print_graph/graph_variables.py
gui/iode_gui/menu/print_graph/print_tables.py
gui/iode_gui/menu/print_graph/print_variables.py
gui/iode_gui/menu/workspace/workspace_extrapolate_variables.py
gui/iode_gui/text_edit/completer.py
gui/iode_gui/text_edit/report_editor.py

GUI PYTHON: fixed autocomplete feature not including IODE objects names

---

cpp_api/KDB/kdb_abstract.cpp
cpp_api/KDB/kdb_global.cpp
cpp_api/KDB/kdb_identities.cpp
cpp_api/KDB/kdb_variables.cpp
cpp_api/compute/estimation.cpp
cpp_api/compute/simulation.cpp
cpp_api/computed_table/computed_table.cpp
cpp_api/utils/super.cpp
cpp_api/utils/super.h
gui/iode_gui/super.py
pyiode/iode/super.py
pyiode/iode/util.py
pyiode/super.cpp
pyiode/super.h
pyiode/super.pyx
pyiode/tests/tests.pxd
pyiode/tests/tests.pyx
tests/test_python/test_cython_iode.py

PYTHON: Better handling errors from the C function kerror in the cython wrapper 

---

.gitignore
CONTRIBUTE.md
pyiode/CMakeLists.txt
pyiode/condarecipe/iode/meta.yaml.in

PYTHON + CONDA: added build script meta.yml for building iode as a conda package

---

api/objs/k_pack.c
api/objs/k_tbl.c
cpp_api/KDB/kdb_equations.cpp
cpp_api/KDB/kdb_tables.cpp
cpp_api/objects/equation.cpp
cpp_api/objects/table.cpp
pyiode/iode/iode_database/tables_database.py
pyiode/iode/objects/table.py
pyiode/objects/table.pyx
tests/test_cpp_api/test_kdb_equations.cpp
tests/test_cpp_api/test_kdb_tables.cpp
tests/test_cpp_api/test_table.cpp

C++ API: fixed hash functions for the Tables database

---

.gitignore
CMakeLists.txt
api/conversion/CMakeLists.txt
api/conversion/export.h
api/conversion/import.h
api/conversion/k_ecsv.cpp
api/conversion/k_edif.cpp
api/conversion/k_emain.cpp
api/conversion/k_etsp.cpp
api/conversion/k_ewks.cpp
api/conversion/k_iasc.cpp
api/conversion/k_ibst.cpp
api/conversion/k_idif.cpp
api/conversion/k_igem.cpp
api/conversion/k_imain.cpp
api/conversion/k_inis.cpp
api/conversion/k_iprn.cpp
api/conversion/k_irasc.cpp
api/conversion/k_itxt.cpp
api/conversion/k_rules.cpp
api/conversion/k_wks.cpp
pyiode/iode/iode_database/variables_database.py
pyiode/iode_database/variables_database.pyx
scr4/s_strs.h
scr4/s_swap.h

C API: converted all C source files from the 'conversion' directory to C++ source files

---

doc/source/changes/v7.0.3.rst.inc
gui/iode_gui/color_theme.py
gui/iode_gui/iode_objs/views/abstract_table_view.py
gui/iode_gui/main.py
gui/iode_gui/main_widgets/tab_widget/tab_widget.py
gui/iode_gui/main_window.py
gui/iode_gui/menu/file/file_settings.py
gui/iode_gui/menu/file/file_settings.ui
gui/iode_gui/settings.py
gui/iode_gui/tabs/tab_abstract.py
gui/iode_gui/tabs/tab_report.py
gui/iode_gui/text_edit/highlighter.py
gui/iode_gui/utils.py.in
gui/pyproject.toml.in

GUI: Allow users to choose the displayed colors in the IODE report editor

---

doc/source/changes/v7.0.3.rst.inc
gui/iode_gui/iode_objs/models/abstract_table_model.py
gui/iode_gui/tabs/iode_objs/tab_database.py

GUI: (VariablesWidget) reset mode when the Variables database is loaded or cleared

---

doc/source/changes/v7.0.3.rst.inc
gui/iode_gui/iode_objs/edit/edit_equation.py

GUI: enhance EditEquationDialog to always set sample based on equation or variables workspace
